### ISSUE TITLE
Crash when starting recording

### ISSUE THREAD

**Issue by opk12** [yakovlevegor/DroidRec#3]
When I click `Start recording` the app asks for permission, then crashes.

```
04-30 14:27:25.978 25827 25827 D AndroidRuntime: Shutting down VM
04-30 14:27:25.979 25827 25827 E AndroidRuntime: FATAL EXCEPTION: main
04-30 14:27:25.979 25827 25827 E AndroidRuntime: Process: com.yakovlevegor.DroidRec, PID: 25827
04-30 14:27:25.979 25827 25827 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.yakovlevegor.DroidRec.ScreenRecorder@a5be2f2 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3787)
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        at android.app.ActivityThread.-wrap23(ActivityThread.java)
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6816)
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
04-30 14:27:25.979 25827 25827 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        at com.yakovlevegor.DroidRec.ScreenRecorder.onStartCommand(ScreenRecorder.java:159)
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3770)
04-30 14:27:25.979 25827 25827 E AndroidRuntime:        ... 8 more
```

I am using the f-droid version on Android 7.1

**Comment by yakovlevegor** [comment]
I've added checks for intent existence. Crashes will be prevented, but the error still persists.

**Comment by opk12** [comment]
Hello. I just opened #4. It blocks usage for me and I would like to report back after it is fixed.

Meanwhile: I am not familiar with the Android API to know what this means, but [Service.onStartCommand()](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int)) says `intent - This may be null if the service is being restarted after its process has gone away, and it had previously returned anything except START_STICKY_COMPATIBILITY.`

**Comment by yakovlevegor** [comment]
Tested the application in emulator on Android 7.1.1 - the recording starts, but then the screen halts and application crashes. Will try to figure out what's wrong.

**Comment by yakovlevegor** [comment]
Apparently, now the same happens on Android 12.

**Comment by yakovlevegor** [comment]
@Symphonic3648 I ran it in an emulator, it crashes immediately after the recording starts. With 11 everything works fine though.

**Comment by yakovlevegor** [comment]
For 7.1.1, it shows that the error is an "illegal surface".
```
11-03 02:51:17.004  1689  1710 E WindowManager: Unhandled exception in Window Manager
11-03 02:51:17.004  1689  1710 E WindowManager: java.lang.IllegalArgumentException: Illegal Surface, could not enable async mode. Was this Surface created with singleBufferMode?
11-03 02:51:17.004  1689  1710 E WindowManager: 	at android.view.SurfaceControl.nativeSetDisplaySurface(Native Method)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:686)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.display.DisplayDevice.setSurfaceInTransactionLocked(DisplayDevice.java:196)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.display.VirtualDisplayAdapter$VirtualDisplayDevice.performTraversalInTransactionLocked(VirtualDisplayAdapter.java:251)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.display.DisplayManagerService.performTraversalInTransactionLocked(DisplayManagerService.java:866)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.display.DisplayManagerService.performTraversalInTransactionFromWindowManagerInternal(DisplayManagerService.java:331)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.display.DisplayManagerService.-wrap15(DisplayManagerService.java)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.display.DisplayManagerService$LocalService.performTraversalInTransactionFromWindowManager(DisplayManagerService.java:1620)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.applySurfaceChangesTransaction(WindowSurfacePlacer.java:887)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner(WindowSurfacePlacer.java:321)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:236)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:184)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:8369)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at android.os.Looper.loop(Looper.java:154)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-03 02:51:17.004  1689  1710 E WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by yakovlevegor** [comment]
Okay, and this is for Android 12. Those two are not really related.
```
11-03 02:21:10.391 10800 10800 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.yakovlevegor.DroidRec.ScreenRecorder@7e2a2e0 with Intent { act=com.yakovlevegor.DroidRec.START_RECORDING cmp=com.yakovlevegor.DroidRec/.ScreenRecorder }: java.lang.IllegalArgumentException: com.yakovlevegor.DroidRec: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
11-03 02:21:10.391 10800 10800 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4703)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2181)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: com.yakovlevegor.DroidRec: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
11-03 02:21:10.391 10800 10800 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:750)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at android.app.PendingIntent.getService(PendingIntent.java:712)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at com.yakovlevegor.DroidRec.ScreenRecorder.screenRecordingStart(ScreenRecorder.java:306)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at com.yakovlevegor.DroidRec.ScreenRecorder.actionStart(ScreenRecorder.java:215)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at com.yakovlevegor.DroidRec.ScreenRecorder.onStartCommand(ScreenRecorder.java:176)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4685)
11-03 02:21:10.391 10800 10800 E AndroidRuntime: 	... 9 more
```

**Comment by yakovlevegor** [comment]
The error occurs on 7.1.1 only when MediaRecorder is called with `setVideoSize`, without that option the recording proceeds as usual.

**Comment by yakovlevegor** [comment]
The gimmick is to get the supported format right. It just doesn't work with getting Metrics for some devices, need to get a specific **supported** resolution to record screen.

**Comment by yakovlevegor** [comment]
Okay, as I need to maintain this hell, I'll replace everything from API 26 with MediaMuxer - writing to file descriptor was introduced only since that API level. And before API 26 I'll keep MediaRecorder with fixed resolution the device can support.

**Comment by yakovlevegor** [comment]
Only MediaMuxer too doesn't want to record unsupported resolutions.

**Comment by yakovlevegor** [comment]
The problem seems to be fixed since API 27 (Android Oreo 8.1). Until then, I'll need to make a resolution choosing function.

**Comment by yakovlevegor** [comment]
Oh, nevermind. That's the android's local player bug.

**Comment by yakovlevegor** [comment]
But for API 25 and lower it crashes.

**Comment by yakovlevegor** [comment]
This should be settled now.

**Comment by yakovlevegor** [comment]
1.5 just came out, the fix is in the latest release. Closing this now.

**Comment by opk12** [comment]
I confirm that 1.5 works on my device. Thank you!
